### PR TITLE
Only tick if the ticker is disabled

### LINKED ISSUE #457: Spinner running faster than "steady tick" duration in v0.17
When upgrading to v0.17, I noticed that the spinner may update *faster* than the rate set in `.enable_steady_tick(…)`.

Background: I use `.enable_steady_tick(…)` to get a consistent look of my progress bar spinner animation, independent from the actual speed of `.inc(…)` calls (which I don't know in advance - it might be faster or slower than the rate set for the steady tick). If I update the bar at a low rate, everything is fine. But if I call `.inc(…)` *faster* than the rate set in `.enable_steady_tick(…)`, I would still expect the spinner to update at the low refresh rate - instead of flickering arbitrarily fast in v0.17. At least this is how it worked in v0.16, and the name of the function (steady tick) seems to indicate that this is the expected outcome, even if the [documentation](https://docs.rs/indicatif/latest/indicatif/struct.ProgressBar.html#method.enable_steady_tick) refers to a use case where the bar is updated at a low speed.

To reproduce this, compare the output of the two programs below, with v0.16 and v0.17 as respective `indicatif` versions:

## v0.16 version (works fine, spinner updates every 200ms)

```rs
use indicatif::{ProgressBar, ProgressStyle};
use std::thread;
use std::time::Duration;

fn main() {
    let steps = 10000;

    let progressbar_style = ProgressStyle::default_spinner()
        .template(" {spinner} {wide_bar}");

    let bar = ProgressBar::new(steps);
    bar.set_style(progressbar_style);
    bar.enable_steady_tick(200);

    for _ in 0..steps {
        bar.inc(1);
        thread::sleep(Duration::from_millis(1));
    }
}
````

## v0.17 version (spinner updates very fast, presumably every 1ms)
```rs
use indicatif::{ProgressBar, ProgressStyle};
use std::thread;
use std::time::Duration;

fn main() {
    let steps = 10000;

    let progressbar_style = ProgressStyle::default_spinner()
        .template(" {spinner} {wide_bar}")
        .unwrap();

    let bar = ProgressBar::new(steps);
    bar.set_style(progressbar_style);
    bar.enable_steady_tick(Duration::from_millis(200));

    for _ in 0..steps {
        bar.inc(1);
        thread::sleep(Duration::from_millis(1));
    }
}

```

### PR DESCRIPTION
**Pull request by djc**
Fix a regression from #417 to fix #457.

Of the 4 callers of `BarState::tick()`, changed three to no longer tick if the ticker is enabled:

* `ProgressBar::inc()`
* `ProgressBar::set_position()`
* `ProgressBar::update()`

The fourth is `ProgressBar::tick()`, which already only ticked if the ticker was disabled.

### CODE REVIEW

File: tests/render.rs [hunk 1]
```diff
@@ -339,7 +339,7 @@ fn ticker_drop() {
                 .with_finish(ProgressFinish::AndLeave)
                 .with_message(format!("doing stuff {}", i)),
         );
-        new_spinner.enable_steady_tick(Duration::from_millis(50));
+        new_spinner.enable_steady_tick(Duration::from_millis(100));
```
Comment (djc) [inline tests/render.rs:342]: There was a test failure on Windows only, so I'm guessing that's just a timing artefact?

**Comment by djc** [comment]
Seems like the performance impact here is negligible (based on running `cargo run --release --example fastbar`), although it's a little ugly that we have to lock another mutex.

File: tests/render.rs (hunk 1 above)
Comment (chris-laplante) [reply tests/render.rs:342]: Yes, I think so

**Review by chris-laplante — APPROVED** [review]
