### PR TITLE
Fix attempt to subtract with overflow (#582)

### LINKED ISSUE #582: Attempt to subtract with overflow when output exceeds terminal height
I am observing `attempt to subtract with overflow` on this line: https://github.com/console-rs/indicatif/blob/40b40d29b6d06ae18c40b829f77e9c43bcebd7af/src/draw_target.rs#L534

`self.lines.len() >= self.orphan_lines_count` holds prior to entering this loop: https://github.com/console-rs/indicatif/blob/40b40d29b6d06ae18c40b829f77e9c43bcebd7af/src/draw_target.rs#L501

And `real_len >= idx` holds at the start of each iteration of that loop.

Those two facts causes me to squint at this `if` block: https://github.com/console-rs/indicatif/blob/40b40d29b6d06ae18c40b829f77e9c43bcebd7af/src/draw_target.rs#L517-L519

In particular, commenting out that `if` block causes my panics to go away.

I don't completely understand the purpose of that `if` block, but maybe it can go away?

(indicatif is a great tool, BTW.)

### PR DESCRIPTION
**Pull request by smoelius**
Fixes #582 

The test `orphan_lines` reproduces the panic. The test `orphan_lines_message_above_progress_bar` tries to ensure that messages are still printed correctly following the fix.

The proposed fix is to effectively ignore `self.orphan_lines_count` many lines from `real_len` when comparing `real_len` to the terminal height.

@oli-obk Would you be able to glance at this? :pray:

### CODE REVIEW

**Review by djc — APPROVED** [review]
LGTM, thanks for digging into this! Will leave this open for other reviews, feel free to ping me in a week or so.

File: src/draw_target.rs [hunk 1]
```diff
@@ -514,7 +515,11 @@ impl DrawState {
                 // subtract with overflow later.
                 usize::max(terminal_len, 1)
             };
-            if real_len + diff > term_height {
+            // Don't consider orphan lines when comparing to terminal height.
+            debug_assert!(idx <= real_len);
+            if self.orphan_lines_count <= idx
+                && real_len - self.orphan_lines_count + diff > term_height
```
Comment (oli-obk) [inline src/draw_target.rs:521]: how does `idx` play into this? It just counts entries, not lines.

Comment (smoelius) [reply src/draw_target.rs:521]: Please forgive me, I don't know the precise meanings of these terms ("entries" and "lines").

But what I seem to observe is this. Following a call to `println` with a string containing `n` newlines, `self.orphan_lines_count` will be (at least) `n + 1`, and `self.lines` will contain (at least) `n + 1` elements.

The purpose of checking `idx` is see whether all of those orphan lines have been processed.

Comment (smoelius) [reply src/draw_target.rs:521]: Thanks for clarifying.

> we're trying to keep `real_len < term_height`

Is that really what we want, though? Not `real_len - self.orphan_lines_count < term_height`?

To be more precise, isn't it that we want to keep the vertical space of the displayed progress bars less than `term_height`?

> So I think your issue should also be fixable by comparing against `real_len` instead of `idx`

Here's why that suggestion gives me pause. Suppose we break with `idx < self.orphan_lines_count`. Then some number of orphan lines have not been drawn. In other words, the user called `println`, but some portion of the output has not been shown. Isn't that undesirable?

Wouldn't we want to show those lines (possibly allowing them to scroll off the top of the screen), and then draw just as many progress bars will fit?

Comment (oli-obk) [reply src/draw_target.rs:521]: ah... right.

In that case, isn't even `idx` causing `println` lines to disappear?
If I understand you correctly, we'll always want to render orphan lines, and ignore them in the height math, acting as if they don't contribute to the terminal space that gets used up.

So... do we actually want `(real_len + diff).saturating_sub(self.orphan_lines_count) > term_height` without any other checks?

Comment (djc) [reply src/draw_target.rs:521]: @chris-laplante maybe you want to weigh in here as well?

Comment (smoelius) [reply src/draw_target.rs:521]: > If I understand you correctly, we'll always want to render orphan lines, and ignore them in the height math, acting as if they don't contribute to the terminal space that gets used up.

That's how I think of it, yes.

But I don't see how these follow.
> In that case, isn't even `idx` causing `println` lines to disappear?

> So... do we actually want `(real_len + diff).saturating_sub(self.orphan_lines_count) > term_height` without any other checks?

If we were try to attach "units" to these variables, `self.orphan_lines_count` and `idx` and would count "unformatted lines", but `real_len` would count "formatted (i.e,. narrower than the terminal) lines", correct?

So wouldn't `(real_len + diff).saturating_sub(self.orphan_lines_count)` be a kind of "type error," because it tries to add a formatted line count (`real_len + diff`) to an unformatted line count (`self.orphan_lines_count`)?

Comment (chris-laplante) [reply src/draw_target.rs:521]: > @chris-laplante maybe you want to weigh in here as well?

I'll try to take a look later this week, sorry, a little short on time for now :(

Comment (smoelius) [reply src/draw_target.rs:521]: @oli-obk Did you have any further thoughts on this?

Comment (oli-obk) [reply src/draw_target.rs:521]: I assumed the `orphan_lines_count` was the real printed lines count. If that is not true, then your reasoning is correct and we need a way to fix that.

Comment (smoelius) [reply src/draw_target.rs:521]: To help increase confidence, I updated the `orphan_lines_message_above_progress_bar` test to generate orphan lines that wrap around the terminal.

From what I can tell, the fix seems to handle those lines correctly.

**Review by oli-obk — APPROVED** [review]

**Comment by chris-laplante** [comment]
> To whomever keeps approving the workflows: thank you. 🙏

We gotchu :)

**Review by djc — APPROVED** [review]

**Comment by djc** [comment]
@chris-laplante do you want to do a final review before (squash and) merge?

@smoelius thanks for your work in getting this right, and @oli-obk thanks for the reviews!

**Review by chris-laplante — APPROVED** [review]
Looks good to me! Thanks for the new tests too :)
